version: '3.9'

x-base_service: &base_service
    ports:
      - "7860:7860"
    volumes:
      - &v1 ./cache:/cache
      - &v2 ./output:/output
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]

name: webui-docker

services:
  download:
    build: ./services/download/
    profiles: ["download"]
    volumes:
      - *v1

  hlky:
    <<: *base_service
    profiles: ["hlky"]
    build: ./services/hlky/
    environment:
      - CLI_ARGS=--optimized-turbo

  automatic1111: &automatic
    <<: *base_service
    profiles: ["auto"]
    build: ./services/AUTOMATIC1111
    volumes:
      - *v1
      - *v2
      - ./services/AUTOMATIC1111/config.json:/stable-diffusion-webui/config.json
    environment:
      - CLI_ARGS=--ckpt /cache/models/model.ckpt --allow-code --medvram

  automatic1111-cpu:
    <<: *automatic
    profiles: ["auto-cpu"]
    deploy: {}
    environment:
      - CLI_ARGS=--ckpt /cache/models/model.ckpt --no-half --precision full

  automatic1111-waifu:
    <<: *base_service
    profiles: ["auto-waifu"]
    build: ./services/AUTOMATIC1111
    volumes:
      - *v1
      - *v2
      - ./services/AUTOMATIC1111/config.json:/stable-diffusion-webui/config.json
    environment:
      - CLI_ARGS=--ckpt /cache/models/wd.ckpt --allow-code --medvram

  lstein:
    <<: *base_service
    profiles: ["lstein"]
    build: ./services/lstein/
    environment:
      - PRELOAD=false
      - CLI_ARGS=

  karaage:
    <<: *base_service
    profiles: ["karaage"]
    build: ./services/karaage/
    environment:
      - PRELOAD=false
      - CLI_ARGS=
